# SPDX-License-Identifier: Apache-2.0
---

# When SAP HANA Scale-Out is used, if host name is not in original specifications then strip suffix node number from host name
- name: SAP VM Provision - KubeVirt - Set fact when performing SAP HANA Scale-Out
  ansible.builtin.set_fact:
    __sap_vm_provision_fact_scaleout_origin_hostname: "{{ inventory_hostname | regex_replace('^(.+?)\\d*$', '\\1') }}"
  when:
    - sap_vm_provision_calculate_sap_hana_scaleout_active_coordinator is defined
    - not inventory_hostname in __sap_vm_provision_host_dict_plan.keys()

- name: SAP VM Provision - KubeVirt - Set fact for VM name
  ansible.builtin.set_fact:
    __sap_vm_provision_fact_vm_name: "{{ inventory_hostname }}"

- name: SAP VM Provision - KubeVirt - Set fact for VM config
  ansible.builtin.set_fact:
    __sap_vm_provision_fact_vm_config: "{{ __sap_vm_provision_host_dict_spec }}"

- name: SAP VM Provision - KubeVirt - Set fact for download OS Image
  ansible.builtin.set_fact:
    __sap_vm_provision_fact_os_image: |-
      {%- set disks_map = [
        {
          'metadata': { 'name': (__sap_vm_provision_fact_vm_name + '-boot' | replace('_', '-')) },
          'spec' : {
            'source' : {
              'registry' : {
                'url': __sap_vm_provision_fact_vm_config.os_image.url,
                'pullMethod': 'node'
              },
            },
            'storage' : {
              'accessModes': __sap_vm_provision_fact_vm_config.os_image.access_modes | d(['ReadWriteMany']),
              'resources': {
                'requests': {
                  'storage': __sap_vm_provision_fact_vm_config.os_image.size
                }
              }
            }
          }
        }
      ] -%}
      {{ disks_map }}
  when: __sap_vm_provision_fact_vm_config.os_image.url | d('') | length > 0

- name: SAP VM Provision - KubeVirt - Set fact for existing OS Image
  ansible.builtin.set_fact:
    __sap_vm_provision_fact_os_image: |
      {%- set disks_map = [
        {
          'metadata': { 'name': (__sap_vm_provision_fact_vm_name + '-boot' | replace('_', '-')) },
          'spec' : {
            'source' : {
              'pvc' : {
                'name': __sap_vm_provision_fact_vm_config.os_image.source_pvc_name,
                'namespace': __sap_vm_provision_fact_vm_config.os_image.namespace
              },
            },
            'storage' : {
              'accessModes': __sap_vm_provision_fact_vm_config.os_image.access_modes | d(['ReadWriteMany']),
              'resources': {
                'requests': {
                  'storage': __sap_vm_provision_fact_vm_config.os_image.size
                }
              }
            }
          }
        }
      ] -%}
      {{ disks_map }}
  when:
    - __sap_vm_provision_fact_vm_config.os_image.source_pvc_name | d('') | length > 0
    - __sap_vm_provision_fact_vm_config.os_image.namespace | d('') | length > 0

- name: SAP VM Provision - KubeVirt - Set fact for storage volume template map
  ansible.builtin.set_fact:
    __sap_vm_provision_fact_storage_disks_map: |-
      {% set disks_map = [] -%}
      {% for storage_item in __sap_vm_provision_fact_vm_config.storage_definition -%}
          {% set vol = disks_map.extend([
          {
            'metadata': { 'name': (__sap_vm_provision_fact_vm_name + '-' + storage_item.name | replace('_', '-')) },
            'spec' : {
              'source' : {
                'blank' : {}
              },
              'storage' : {
                'accessModes': storage_item.access_modes | d(['ReadWriteMany']),
                'resources': {
                  'requests': {
                    'storage': ((storage_item.disk_size | default(0)) | string) + 'Gi',
                  }
                },
                'storageClassName': storage_item.disk_type | default(''),
              }
            }
          }]) %}
      {%- endfor %}
      {{ disks_map }}

- name: SAP VM Provision - KubeVirt - Set fact for storage volumes attachment list
  ansible.builtin.set_fact:
    __sap_vm_provision_fact_storage_disk_name_list: |-
      {% set disks_simple_map = [] -%}
      {% for list_item in __sap_vm_provision_fact_os_image | d([]) -%}
        {% set vol = disks_simple_map.extend([
        {
          'name': list_item.metadata.name,
          'dataVolume': { 'name': list_item.metadata.name },
        }
        ]) %}
      {%- endfor %}
      {% for list_item in __sap_vm_provision_fact_storage_disks_map -%}
        {% set vol = disks_simple_map.extend([
        {
          'name': list_item.metadata.name,
          'dataVolume': { 'name': list_item.metadata.name },
        }
        ]) %}
      {%- endfor %}
      {{ disks_simple_map }}


- name: SAP VM Provision - KubeVirt - Set fact for disk list
  ansible.builtin.set_fact:
    __sap_vm_provision_fact_storage_disk_list: |-
      {% set disks_list_simple = [] -%}
        {% set vol = disks_list_simple.extend([
        {
          'name': __sap_vm_provision_fact_vm_name + '-boot' | replace('_', '-'),
          'bootOrder': 1,
          'disk': {
              'bus': 'virtio',
              'io': 'native'
         }
        },
        {
          'name': 'cloudinit',
          'io': 'native',
          'disk': {
              'bus': 'virtio'
         }
        },
        ]) %}
      {% for list_item in __sap_vm_provision_fact_storage_disks_map -%}
        {% set vol = disks_list_simple.extend([
        {
          'name': list_item.metadata.name,
          'io': 'native',
          'disk': {
              'bus': 'virtio'
         }
        }
        ]) %}
      {%- endfor %}
      {{ disks_list_simple }}

- name: SAP VM Provision - KubeVirt - Set fact for cloud-init volume
  ansible.builtin.set_fact:
    __sap_vm_provision_fact_cloud_init_volume:
      - name: cloudinit
        disk:
          bus: virtio
        cloudInitNoCloud: "{{ __sap_vm_provision_fact_vm_config.cloudinit }}"

- name: SAP VM Provision - KubeVirt - Set fact for network interfaces
  ansible.builtin.set_fact:
    __sap_vm_provision_fact_network_interfaces: |-
      {% set netifs = [] -%}
      {% for list_item in __sap_vm_provision_fact_vm_config.network_definition -%}
        {% set ifs = netifs.extend([
        {
          list_item.type: {},
          'model': list_item.model,
          'name': list_item.name,
        }
        ]) %}
      {%- endfor %}
      {{ netifs }}

- name: SAP VM Provision - KubeVirt - Set fact for networks definition
  ansible.builtin.set_fact:
    __sap_vm_provision_fact_networks_definition: |-
      {% set networks = [] -%}
      {% for list_item in __sap_vm_provision_fact_vm_config.network_definition -%}
        {% set ifs = networks.extend([
        {
          'name': list_item.name,
          'multus': { 'networkName': list_item.networkName}
        }
        ]) %}
      {%- endfor %}
      {{ networks }}

- name: SAP VM Provision - KubeVirt - Fail if hugepages are not used but dedicated CPU placement and/or NUMA guestMappingPassthrough
  ansible.builtin.fail:
    msg: |
      FAIL: Invalid CPU configuration: dedicatedCpuPlacement=true cannot be used
      together with numa.guestMappingPassthrough without huge pages.
  when:
    - sap_vm_provision_kubevirt_vm_performance_cpu_settings.dedicatedCpuPlacement | d(false) | bool
      or sap_vm_provision_kubevirt_vm_performance_cpu_settings.numa.guestMappingPassthrough is defined
    - __sap_vm_provision_fact_vm_config.kubevirt_vm_memory_hypervisor_hugepages is defined
    - not (__sap_vm_provision_fact_vm_config.kubevirt_vm_memory_hypervisor_hugepages | bool)

- name: SAP VM Provision - KubeVirt - Set fact for memory definition
  ansible.builtin.set_fact:
    __sap_vm_provision_fact_memory_definition: >-
      {{
        {
          'guest': __sap_vm_provision_fact_vm_config.kubevirt_vm_memory_gib ~ 'Gi'
        }
        | combine(
            (__sap_vm_provision_fact_vm_config.kubevirt_vm_memory_hypervisor_hugepages | default(true)) | ternary(
              {
                 'hugepages': {
                   'pageSize': (__sap_vm_provision_fact_vm_config.kubevirt_vm_memory_hypervisor_hugepages | default('1Gi'))
                 }
              },
              {}
            )
          )
      }}

- name: SAP VM Provision - KubeVirt - Set fact for VM deploy config
  ansible.builtin.set_fact:
    __sap_vm_provision_fact_vm_deploy_config:
      evictionStrategy: "{{ sap_vm_provision_kubevirt_vm_eviction_strategy }}"
      volumes: "{{ __sap_vm_provision_fact_storage_disk_name_list + __sap_vm_provision_fact_cloud_init_volume }}"
      networks: "{{ __sap_vm_provision_fact_networks_definition }}"
      domain:
        ioThreadsPolicy: shared
        hostname: "{{ __sap_vm_provision_fact_vm_name }}"
        terminationGracePeriodSeconds: 1800 # 30 minutes after stop request before VM is force terminated
        resources:
          requests:
            # memory + overhead for container runtime)
            memory: "{{ __sap_vm_provision_fact_vm_config.kubevirt_vm_memory_gib
              + sap_vm_provision_kubevirt_vm_container_memory_overhead }}Gi"

        devices:
          downwardMetrics: {}
          networkInterfaceMultiqueue: true
          blockMultiQueue: true
          autoattachMemBalloon: false
          disks: "{{ __sap_vm_provision_fact_storage_disk_list }}"
          interfaces: "{{ __sap_vm_provision_fact_network_interfaces }}"

        cpu:
          cores: "{{ __sap_vm_provision_fact_vm_config.kubevirt_vm_cpu_cores }}"
          threads: "{{ __sap_vm_provision_fact_vm_config.kubevirt_vm_cpu_smt }}"

        memory: "{{ __sap_vm_provision_fact_memory_definition }}"

- name: SAP VM Provision - KubeVirt - Apply CPU performance settings
  ansible.builtin.set_fact:
    __sap_vm_provision_fact_vm_deploy_config: >-
      {{ __sap_vm_provision_fact_vm_deploy_config
        | combine({'domain': { 'cpu': __sap_vm_provision_fact_vm_deploy_config.domain.cpu
        | combine(sap_vm_provision_kubevirt_vm_performance_cpu_settings)}}, recursive=True) }}

- name: SAP VM Provision - KubeVirt - Provision KubeVirt Virtual Machine
  kubevirt.core.kubevirt_vm:
    api_version: "{{ api_version | default(omit) }}"
    persist_config: "{{ persist_config | default(omit) }}"

    ## Virtual Machine target Hypervisor definition
    namespace: "{{ sap_vm_provision_kubevirt_vm_target_namespace }}" # Target namespace

    ## Virtual Machine definition
    state: present
    running: true
    wait: true  # ensure Virtual Machine in ready state before exiting Ansible Task
    wait_sleep: 30  # 30 second poll for ready state
    wait_timeout: 600  # 10 minute wait for ready state
    # Do not replace existing Virtual Machine with same name
    force: "{{ sap_vm_provision_overwrite_vm | default(false) }}"
    name: "{{ __sap_vm_provision_fact_vm_name }}"
    labels:
      app: "{{ __sap_vm_provision_fact_vm_name }}"
    # Virtual Disk volume definitions
    data_volume_templates: "{{ __sap_vm_provision_fact_storage_disks_map + __sap_vm_provision_fact_os_image }}"
    spec: "{{ __sap_vm_provision_fact_vm_deploy_config }}"
  register: __sap_vm_provision_register_provision_host_single
  no_log: "{{ __sap_vm_provision_no_log }}"

- name: SAP VM Provision - KubeVirt - Check VM status
  kubevirt.core.kubevirt_vm_info:
    name: "{{ __sap_vm_provision_fact_vm_name }}"
    namespace: "{{ sap_vm_provision_kubevirt_vm_target_namespace }}"
  register: __sap_vm_provision_register_provision_host_single_info
  no_log: "{{ __sap_vm_provision_no_log }}"

- name: SAP VM Provision - KubeVirt - Get VMI details
  kubernetes.core.k8s_info:
    api_version: kubevirt.io/v1
    kind: VirtualMachineInstance
    namespace: "{{ sap_vm_provision_kubevirt_vm_target_namespace }}"
    name: "{{ __sap_vm_provision_fact_vm_name }}"
  register: __sap_vm_provision_register_provision_vmi_info
  until: __sap_vm_provision_register_provision_vmi_info.resources[0].status.interfaces[0].ipAddress is defined
  retries: 10
  delay: 30


# Other platforms are using provisioned results to get IP address generated during provisioning,
# but for KubeVirt we need to get IP address from VMI details, since provisioning result does not contain IP address.
- name: SAP VM Provision - KubeVirt - Combine details of provisioned hosts into one list
  ansible.builtin.set_fact:
    __sap_vm_provision_fact_provisioned_hosts: "{{ __sap_vm_provision_fact_provisioned_hosts + [__merged_results] }}"
  # Append keys to provisioning result, that are not part of default return dictionary.
  vars:
    __merged_results:
      "{{ __sap_vm_provision_register_provision_vmi_info
        | combine({'host_node': inventory_hostname},
        {'sap_host_type': __sap_vm_provision_host_dict_spec.sap_host_type},
        {'sap_system_type': (__sap_vm_provision_host_dict_spec.sap_system_type | d(''))},
        {'__sap_vm_provision_fact_private_ip': __sap_vm_provision_register_provision_vmi_info.resources[0].status.interfaces[0].ipAddress}) }}"
