---
- name: Include worker node mkfs loop
  ansible.builtin.include_tasks:
    file:  "platform/{{ sap_hypervisor_node_preconfigure_platform }}/storage/worker-mkfs-loop.yml"
  loop: "{{ sap_hypervisor_node_preconfigure_cluster_config.workers }}"
  loop_control:
    loop_var: __sap_hypervisor_node_preconfigure_register_worker
    index_var: __sap_hypervisor_node_preconfigure_register_worker_nr

- name: Create systemd files for local storage handling
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      metadata:
        annotations:
        labels:
          machineconfiguration.openshift.io/role: worker
        name: 50-hpp-local
      spec:
        config:
          ignition:
            version: 2.2.0
          systemd:
            units:
              - contents: |
                  [Install]
                  WantedBy=local-fs.target
                  [Unit]
                  Description=Create mountpoint {{ sap_hypervisor_node_preconfigure_hpp_mountpoint }}, mount and set selinux flag
                  Before=kubelet.service
                  [Service]
                  Type=oneshot
                  ExecStart=/bin/mkdir -p {{ sap_hypervisor_node_preconfigure_hpp_mountpoint }}
                  ExecStart=mount {{ sap_hypervisor_node_preconfigure_cluster_config.worker_localstorage_device }} {{ sap_hypervisor_node_preconfigure_hpp_mountpoint }}
                  ExecStart=/usr/bin/chcon -Rt container_file_t  {{ sap_hypervisor_node_preconfigure_hpp_mountpoint }}
                enabled: true
                name: create-mount-localstorage.service

- name: Include wait mcp finished updating
  ansible.builtin.include_tasks:
    file: "platform/{{ sap_hypervisor_node_preconfigure_platform }}/cluster/wait-mcp-finished-updating.yml"

- name: Create hostpath provisioner (HPP)
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
      kind: HostPathProvisioner
      metadata:
        name: hostpath-provisioner
      spec:
        imagePullPolicy: IfNotPresent
        storagePools:
          - name: localstorage
            path: "{{ sap_hypervisor_node_preconfigure_hpp_mountpoint }}"
        workload:
          nodeSelector:
            kubernetes.io/os: linux

- name: Wait for HostPathProvisioner status to become Available
  kubernetes.core.k8s_info:
    api_version: hostpathprovisioner.kubevirt.io/v1beta1
    kind: HostPathProvisioner
    name: hostpath-provisioner
    wait: true
    wait_condition:
      type: Available
      status: "True"
      reason: Complete
    wait_sleep: 30
    wait_timeout: 300

- name: Create storage class for HPP
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: "{{ sap_hypervisor_node_preconfigure_cluster_config.worker_localstorage_storageclass_name }}"
        annotations:
          storageclass.kubernetes.io/is-default-class: "{{ 'true' if sap_hypervisor_node_preconfigure_cluster_config.worker_localstorage_default_storageclass is true else 'false' }}"
      provisioner: kubevirt.io.hostpath-provisioner
      reclaimPolicy: Delete
      volumeBindingMode: WaitForFirstConsumer
      parameters:
        storagePool: localstorage
