---

collections:
  - name: amazon.aws
    type: galaxy
    version: 9.0.0
  - name: community.aws
    type: galaxy
    version: 9.0.0
  - name: azure.azcollection
    type: galaxy
    version: 3.2.0
  - name: google.cloud
    type: galaxy
    version: 1.1.3
  # Replace with ibm.cloud in future, legacy Ansible Collection uses hidden on-the-fly Terraform files in /var/tmp/ansible/ibmcloud)
  - name: ibm.cloudcollection
    type: galaxy
    version: 1.71.2
  - name: ovirt.ovirt
    type: galaxy
    version: 3.1.2
  - name: openstack.cloud
    type: galaxy
    version: 2.1.0
  - name: vmware.vmware_rest
    type: galaxy
    version: 4.5.0
  - name: cloud.common
    type: galaxy
    version: 4.0.0
  - name: cloud.terraform
    type: galaxy
    version: 3.0.0
  - name: kubevirt.core
    type: galaxy
    version: 1.5.0
  # For Red Hat OpenShift
  - name: community.okd
    type: galaxy
    version: 3.0.1
  - name: ansible.posix
    type: galaxy
    version: '>=1.5.4,<=2.1.0' # check galaxy for the best supported version
