---
- name: Set cluster master nodes unscheduable
  kubernetes.core.k8s:
    state: patched
    definition:
      apiVersion: config.openshift.io/v1
      kind: Scheduler
      metadata:
        name: cluster
      spec:
        mastersSchedulable: false
