---

# vars file for redhat_ocp_virt

###########################################################
# Red Hat OpenShift cluster connection details
###########################################################

# kubeconfig for Red Hat OpenShift cluster connection.
# Needs to contain a valid API token for trident storage operator to work.
# If not provided, the kubeconfig will be read from the environment variables
# KUBECONFIG or K8S_AUTH_KUBECONFIG
# sap_hypervisor_node_preconfigure_kubeconfig:


###########################################################
# Configuration of what should be preconfigured
###########################################################

# Install and configure the host path provisioner (hpp) for a local storage disk
sap_hypervisor_node_preconfigure_install_hpp: false

# Install the trident NFS storage provider
sap_hypervisor_node_preconfigure_install_trident: false

# Should the operators be installed
sap_hypervisor_node_preconfigure_install_operators: true

# Configure the workers?
sap_hypervisor_node_preconfigure_setup_worker_nodes: true


###################################################################################
# Individual worker nodes config details, typically no need to change anything here.
# Requires sap_hypervisor_node_preconfigure_setup_worker_nodes to be set to true.
###################################################################################

# Should the network of the nodes be configured?
sap_hypervisor_node_preconfigure_configure_worker_node_network: true

# Should the cpumanager be enabled? This has to be set to true.
sap_hypervisor_node_preconfigure_enable_cpumanager: true

# Should the kargs be applied to the worker nodes?
sap_hypervisor_node_preconfigure_enable_kargs: true


###########################################################
# Configuration details
###########################################################

# URL of the trident installer package to use
sap_hypervisor_node_preconfigure_install_trident_url: https://github.com/NetApp/trident/releases/download/v25.02.1/trident-installer-25.02.1.tar.gz

# Allow unsupported NICs to be used for SR-IOV?
sap_hypervisor_node_preconfigure_sriov_enable_unsupported_nics: false

# Amount of memory [GiB] to be reserved for the hypervisor on hosts >= 512GiB
sap_hypervisor_node_preconfigure_hypervisor_reserved_ram_host_ge_512: 64 # GiB

# Amount of memory [GiB] to be reserved for the hypervisor on hosts < 512GiB
sap_hypervisor_node_preconfigure_hypervisor_reserved_ram_host_lt_512: 32 # GiB

# Should the check for the minimal amount of be ignored? Minimal amount is 96 GiB
sap_hypervisor_node_preconfigure_ignore_minimal_memory_check: false

# Namespace to be used for the Red Hat Openshift Virtualization Operator
sap_hypervisor_node_preconfigure_ocpv_namespace: openshift-cnv

# Channel to be used for the Red Hat Openshift Virtualization Operator
sap_hypervisor_node_preconfigure_ocpv_subscription_channel: stable

# Namespace to be used for the Red Hat Openshift Nmstate Operator
sap_hypervisor_node_preconfigure_nmstate_namespace: openshift-nmstate

# Mountpoint for hostpath provisioner
sap_hypervisor_node_preconfigure_hpp_mountpoint: /var/localstorage


###########################################################
# Red Hat OpenShift cluster configuration details
###########################################################

# Example configuration for redhat_ocp_virt
sap_hypervisor_node_preconfigure_cluster_config:

  # namespace under which the VMs are created, note this has to be
  # openshift-sriov-network-operator in case of using SR-IOV network
  # devices
  vm_namespace: sap

  # Optional, configuration for trident driver for Netapp NFS filer
  trident:
    management: management.domain.org
    data: datalif.netapp.domain.org
    svm: sap_svm
    backend: nas_backend
    aggregate: aggregate_Name
    username: admin
    password: xxxxx
    storage_driver: ontap-nas
    storage_prefix: ocpv_sap_
    nfs_mount_options: nfsvers=3
    export_policy: default
    storageclass_name: sapstorage  # Name of the storage class (careful, there can only be one SC with this name)
    default_storageclass: True     # Should this storage class be default?

  # CPU cores which will be reserved for kubernetes
  worker_kubernetes_reserved_cpus: "0,1"

  # Storage device used for host path provisioner as local storage.
  worker_localstorage_device: /dev/vdb

  # Name of the storage class for locastorage
  worker_localstorage_storageclass_name: sapstorage

  # Should the local storage class be default?
  worker_localstorage_default_storageclass: True

  # detailed configuration for every worker that should be configured
  workers:

    - name: worker-0                   # name must match the node name
      networks:                        # Example network config

        - name: sapbridge              # using a bridge
          description: SAP bridge
          state: up
          type: linux-bridge
          ipv4:
            enabled: false
            auto-gateway: false
            auto-dns: false
          bridge:
            options:
              stp:
                enabled: false
            port:
              - name: ens1f0           # network IF name

# Additional network interfaces, just shown here for reference
#        - name: storage                # an SR-IOV device
#          interface: ens2f0            # network IF name
#          type: sriov

#        - name: ens2f0                 # Set elevated MTU of 9000
#          type: ethernet               # on parent interface of
#          state: up                    # storagebridge
#          ipv4:
#            dhcp: false
#            enabled: false
#          mtu: 9000

#        - name: storagebridge          # using a bridge
#          bridge:                      # another bridge
#            options:
#              stp:
#                enabled: false
#            port:
#              - name: ens2f0           # network IF name
#          description: storage
#          mtu: 9000
#          ipv4:
#            address:
#              - ip: 192.168.1.10       # IP config
#                prefix-length: 24
#            auto-dns: false
#            auto-gateway: false
#          enabled: true
#          state: up
#          type: linux-bridge
#
#        - name: multi                  # another SR-IOV device
#          interface: ens2f1            # network IF name
#          type: sriov


    - name: worker-1                   # second worker configuration
      networks:                        # Example network config

        - name: sapbridge              # using a bridge
          description: SAP bridge
          state: up
          type: linux-bridge
          ipv4:
            enabled: false
            auto-gateway: false
            auto-dns: false
          bridge:
            options:
              stp:
                enabled: false
            port:
              - name: ens1f0           # network IF name

# Additional network interfaces, just shown here for reference
#        - name: storage                # an SR-IOV device
#          interface: ens2f0            # network IF name
#          type: sriov
#
#        - name: ens2f0                 # Set elevated MTU of 9000
#          type: ethernet               # on parent interface of
#          state: up                    # storagebridge
#          ipv4:
#            dhcp: false
#            enabled: false
#          mtu: 9000
#
#        - name: storagebridge          # create storage bridge
#          bridge:
#            options:
#              stp:
#                enabled: false
#            port:
#              - name: ens2f0           # network IF name
#          description: storage
#          mtu: 9000
#          ipv4:
#            address:
#              - ip: 192.168.1.11       # IP config
#                prefix-length: 24
#            auto-dns: false
#            auto-gateway: false
#          enabled: true
#          state: up
#          type: linux-bridge
#
#        - name: multi                  # another SR-IOV device
#          interface: ens2f1            # network IF name
#          type: sriov
