---
############################################
# Red Hat OpenShift Virtualization         #
############################################

# Namespace where the VM should be created in
sap_vm_provision_ocp_target_namespace: sap

# Username to be created on guest
sap_vm_provision_ocp_os_user: minion

# Password for the above user
sap_vm_provision_ocp_os_user_password:

# Should an existing VM be overwritten?
sap_vm_provision_ocp_overwrite_vm: false

# Kubeconfig file for cluster where VMs should be created
sap_vm_provision_ocp_kubeconfig_path: /path/to/clusterconfigs/kubeconfig

# In order to use secured communication, provide the CA cert bundle for the cluster.
# This can be extracted from the kubeconfig file with the following command from the 
# kubeconfig file:
#   grep certificate-authority-data ${KUBECONFIG} | awk '{ print $2 }' | base64 --decode > cluster-ca-cert.pem
sap_vm_provision_ocp_ca_cert: /path/to/clusterconfigs/cluster-ca-cert.pem

# Admin username for the cluster communication 
sap_vm_provision_ocp_admin_username: kubeadmin

# Password for the above admin user
sap_vm_provision_ocp_admin_password: AAAAA-BBBBB-CCCCC-DDDDD

# API endpoint of the cluster
sap_vm_provision_ocp_endpoint: https://api.cluster.domain.tld:6443

sap_vm_provision_redhat_ocp_virt_host_specifications_dictionary:
  example_host_specification_plan:
    host1: # Hostname, must be 13 characters or less
      # SMT-2 (i.e. 2 CPU Threads per CPU Core) is default for Intel CPU Hyper-Threading, optionally can be altered to SMT-1
      kubevirt_vm_cpu_smt: 2
      kubevirt_vm_cpu_cores: 2
      kubevirt_vm_memory_gib: 24
      #sap_system_type: project_dev # project_dev, project_tst, project_prd
      sap_host_type: hana_primary # hana_primary, hana_secondary, anydb_primary, anydb_secondary, nwas_ascs, nwas_ers, nwas_pas, nwas_aas

      # Provide either an existing PVC or a URL for an OS image  
      os_image:
        # URL for an image to be used 
        url: "docker://registry.redhat.io/rhel8/rhel-guest-image:8.9.0"
        # Name for a PVC to be cloned
        name: "rhel-8.9"
        namespace: openshift-virtualization-os-images
        size: "50Gi"
      network_definition:
        - name: sapbridge
          type: bridge
          networkName: sapbridge-network-definition
          model: virtio
      storage_definition:
        - name: hana
          mountpoint: /hana
          disk_count: 1                  # default: 1
          disk_size: 2048                # size in GB, integer
          disk_type: nas                 # KubeVirt Storage Class
      cloudinit:
        userData: |-
          #cloud-config
          timezone: Europe/Berlin
          hostname: "{{ scaleout_origin_host_spec }}"
          user: {{ sap_vm_provision_ocp_os_user if sap_vm_provision_ocp_os_user is defined }}
          password: {{ sap_vm_provision_ocp_os_user_password if sap_vm_provision_ocp_os_user_password is defined }}
          chpasswd:
            expire: false
          ssh_authorized_keys:
            - "{{ lookup('ansible.builtin.file', sap_vm_provision_ssh_host_public_key_file_path ) }}"
        networkData: |-
          network:
            version: 2
            ethernets:
              eth0:
                dhcp4: true
