---

- name: Set fact to hold loop variables from include_tasks
  ansible.builtin.set_fact:
    register_provisioned_host_all: []

#- name: Set fact for auth - defaults
#  ansible.builtin.set_fact:
#    api_version: "kubevirt.io/v1"
#    validate_certs: "{{ lookup('env', 'K8S_AUTH_VERIFY_SSL') | default(true) }}"
#    persist_config: "{{ default(lookup('env', 'K8S_AUTH_PERSIST_CONFIG')) | default(true) }}"
#    host: "{{ sap_vm_provision_kubevirt_cluster_url | default(lookup('env', 'K8S_AUTH_HOST')) | default(omit) }}" # Target Hypervisor Node

#- name: Set fact for auth - Kubeconfig
#  ansible.builtin.set_fact:
#    kubeconfig: "{{ sap_vm_provision_kubevirt_kubeconfig_path | default(lookup('env', 'K8S_AUTH_KUBECONFIG')) | default(lookup('env', 'KUBECONFIG')) | default(omit) }}"

#- name: Set fact for auth - API Key
#  ansible.builtin.set_fact:
#    api_key: "{{ sap_vm_provision_kubevirt_api_key | default(lookup('env', 'K8S_AUTH_API_KEY')) | default(omit) }}"
#  when: kubeconfig is defined

#- name: Set fact for auth - Username and Passwords
#  ansible.builtin.set_fact:
#    username: "{{ sap_vm_provision_kubevirt_username | default(lookup('env', 'K8S_AUTH_USERNAME')) | default(omit) }}"
#    password: "{{ sap_vm_provision_kubevirt_password | default(lookup('env', 'K8S_AUTH_PASSWORD')) | default(omit) }}"

# - name: Set fact for auth - Alternative
#   ansible.builtin.set_fact:
#     ca_cert: "{{ default(lookup('env', 'K8S_AUTH_SSL_CA_CERT')) | default(omit) }}"
#     client_cert: "{{ default(lookup('env', 'K8S_AUTH_CERT_FILE')) | default(omit) }}"
#     client_key: "{{ default(lookup('env', 'K8S_AUTH_KEY_FILE')) | default(omit) }}"
#     context: "{{ default(lookup('env', 'K8S_AUTH_CONTEXT')) | default(omit) }}"

- name: Log in (obtain access token)
  community.okd.openshift_auth:
    host: "{{ sap_vm_provision_ocp_endpoint }}"
    username: "{{ sap_vm_provision_ocp_admin_username }}"
    password: "{{ sap_vm_provision_ocp_admin_password }}"
#    ca_cert: "{{ sap_vm_provision_ca_cert }}"
    verify_ssl: false
  register: __sap_vm_provision_register_openshift_auth_results

- name: Get a list of all nodes from any namespace
  kubernetes.core.k8s_info:
    host: "{{ sap_vm_provision_ocp_endpoint }}"
    api_key: "{{ __sap_vm_provision_register_openshift_auth_results.openshift_auth.api_key }}"
    kubeconfig: "{{ sap_vm_provision_kubeconfig }}"
    ca_cert: "{{ sap_vm_provision_ca_cert }}"

- name: Provision hosts to OpenShift
  register: register_provisioned_hosts
  ansible.builtin.include_tasks:
    file: "{{ 'platform_' + sap_vm_provision_iac_type }}/{{ sap_vm_provision_iac_platform }}/execute_provision.yml"

- name: Add hosts provisioned to the Ansible Inventory
  register: register_add_hosts
  ansible.builtin.add_host:
    name: "{{ add_item[0].host_node }}"
    groups: "{{ add_item[0].sap_system_type + '_' if (add_item[0].sap_system_type != '') }}{{ add_item[0].sap_host_type }}"
    ansible_host: "{{ add_item[0].reported_devices[0].ips[0].address }}"
    ansible_user: "root"
    ansible_ssh_private_key_file: "{{ sap_vm_provision_ssh_host_private_key_file_path }}"
    ansible_ssh_common_args: -o ConnectTimeout=180 -o ControlMaster=auto -o ControlPersist=3600s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardX11=no
  loop: "{{ ansible_play_hosts | map('extract', hostvars, 'register_provisioned_host_all')  }}"
  loop_control:
    label: "{{ add_item[0].host_node }}"
    loop_var: add_item


# Cannot override any variables from extravars input, see https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence
# Ensure no default value exists for any prompted variable before execution of Ansible Playbook

- name: Set fact to hold all inventory hosts in all groups
  ansible.builtin.set_fact:
    groups_merged_list: "{{ [ [ groups['hana_primary'] | default([]) ] , [ groups['hana_secondary'] | default([]) ] , [ groups['nwas_ascs'] | default([]) ] , [ groups['nwas_ers'] | default([]) ] , [ groups['nwas_pas'] | default([]) ] , [ groups['nwas_aas'] | default([]) ] ] | flatten | select() }}"

- name: Set Ansible Vars
  register: register_set_ansible_vars
  ansible.builtin.include_tasks:
    file: common/set_ansible_vars.yml

  #  - ansible.builtin.debug:
  #      var: register_add_hosts.results

- name: Ansible Task block to execute on target inventory hosts
  delegate_to: "{{ inventory_hostname }}"
  block:

    # Required to collect the remote host's facts for further processing
    # in the following steps
    - name: Gather host facts
      ansible.builtin.setup:

    # Must be set to short hostname,
    # so that command 'hostname' and 'hostname -s' return the short hostname only;
    # otherwise may cause error with SAP SWPM using name.domain.com.domain.com
    - name: Change system hostname (must be set to short name and not FQDN, as required by SAP)
      ansible.builtin.hostname:
        name: "{{ inventory_hostname_short }}"

    - name: Set /etc/hosts
      register: register_etc_hosts_file
      ansible.builtin.include_tasks:
        file: common/set_etc_hosts.yml

    - name: Set /etc/hosts for HA
      register: register_etc_hosts_file_ha
      ansible.builtin.include_tasks:
        file: common/set_etc_hosts_ha.yml
      when:
        - (groups["hana_secondary"] is defined and (groups["hana_secondary"] | length>0)) or (groups["nwas_ers"] is defined and (groups["nwas_ers"] | length>0)) or (groups["anydb_secondary"] is defined and (groups["anydb_secondary"] | length>0))

    - name: Set /etc/hosts for Scale-Out
      register: register_etc_hosts_file_scaleout
      ansible.builtin.include_tasks:
        file: common/set_etc_hosts_scaleout.yml
      when:
        - (groups["hana_primary"] is defined and (groups["hana_primary"] | length>0)) and (sap_hana_scaleout_active_coordinator is defined or sap_hana_scaleout_active_worker is defined or sap_hana_scaleout_standby is defined)

    - name: Set vars for sap_storage_setup Ansible Role
      register: register_ansible_vars_storage
      ansible.builtin.include_tasks:
        file: common/set_ansible_vars_storage.yml

    - name: Register Package Repositories
      ansible.builtin.include_tasks:
        file: common/register_os.yml

    - name: Register Web Forward Proxy
      ansible.builtin.include_tasks:
        file: common/register_proxy.yml
