---
# Define listening port based on target host group. Same ports are used by sap_vm_provision during NLB creation
# 55550 - SAP HANA and SAP AnyDB
# 55551 - SAP SAP NetWeaver ASCS
# 55552 - SAP NetWeaver ERS
# Else ensures that we always return String, not NoneType.
- name: Set fact for temporary listening port
  ansible.builtin.set_fact:
    __sap_vm_temp_vip_port: >-
      {% if groups[sap_vm_temp_vip_group_hana_secondary] | d([]) | length > 0 and inventory_hostname in groups[sap_vm_temp_vip_group_hana_primary] -%}
        55550
      {%- elif groups[sap_vm_temp_vip_group_anydb_secondary] | d([]) | length > 0 and inventory_hostname in groups[sap_vm_temp_vip_group_anydb_primary] -%}
        55550
      {%- elif groups[sap_vm_temp_vip_group_nwas_ers] | d([]) | length > 0 and inventory_hostname in groups[sap_vm_temp_vip_group_nwas_ascs] -%}
        55551
      {%- elif groups[sap_vm_temp_vip_group_nwas_ers] | d([]) | length > 0 and inventory_hostname in groups[sap_vm_temp_vip_group_nwas_ers] -%}
        55552
      {%- else -%}
        {{ '' }}
      {%- endif %}


# Check if defined port is alreadu active and listening
# ss is used as it is present on both SUSE and Red Hat OS without need to install lsof or netstat
- name: Check if temporary port is already open
  ansible.builtin.command:
    cmd: ss -tulnH "sport = :{{ __sap_vm_temp_vip_port }}"
  register: __sap_vm_temp_vip_port_check
  when:
    - __sap_vm_temp_vip_port | length > 0
  changed_when: false


- name: Block to start temporary netcat processes for Load Balancer Health Checks
  when:
    - __sap_vm_temp_vip_address | length > 0
    - __sap_vm_temp_vip_port | length > 0
    - __sap_vm_temp_vip_port_check.stdout is defined and __sap_vm_temp_vip_port_check.stdout | length == 0
    - __sap_vm_temp_vip_prefix | length > 0  # Dont execute if prefix was empty during VIP creation
  block:

    # Get content of ip address show filtered by VIP - Additional execution if VIP was previously created
    - name: Check if VIP is was already attached to network interface
      ansible.builtin.shell:
        cmd: "set -o pipefail && ip --oneline address show | grep {{ __sap_vm_temp_vip_address }}/{{ __sap_vm_temp_vip_prefix }}"
        executable: /bin/bash
      register: __sap_vm_temp_vip_check_ip
      changed_when: false
      ignore_errors: true
      failed_when: false

    # Install netcat package that is used to temporarily listen on ports
    - name: Install netcat package
      ansible.builtin.package:
        name:
          - "{{ 'netcat' if ansible_os_family == 'Suse' else 'nc' }}"
        state: present
      when: __sap_vm_temp_vip_check_ip.stdout | length > 0


    # Start netcat with timeout of 12 hours to ensure that SAP installation has enough time to complete.
    - name: Start temporary 12 hour netcat process for Load Balancer Health Checks during SAP installation
      ansible.builtin.shell: |
        nohup timeout 12h bash -c "while true; do nc -vvv -l -k {{ __sap_vm_temp_vip_port }} ; done" </dev/null >/dev/null 2>&1 &
        sleep 2
      when: __sap_vm_temp_vip_check_ip.stdout | length > 0
