---
- name: Enable CPU Manager by patching MCP worker
  kubernetes.core.k8s:
    state: patched
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      metadata:
        name: worker
        labels:
          custom-kubelet: cpumanager-enabled

- name: Delete kubletconfig for cpumanager
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: KubeletConfig
      metadata:
        name: cpumanager-enabled
      spec:
        machineConfigPoolSelector:
          matchLabels:
            custom-kubelet: cpumanager-enabled
        kubeletConfig:
          cpuManagerPolicy: static
          cpuManagerReconcilePeriod: 5s

- name: Create kubletconfig for cpumanager worker with CPUs reserved for kubernetes
  when: sap_hypervisor_node_preconfigure_cluster_config.worker_kubernetes_reserved_cpus is defined
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: KubeletConfig
      metadata:
        name: cpumanager-enabled
      spec:
        machineConfigPoolSelector:
          matchLabels:
            custom-kubelet: cpumanager-enabled
        kubeletConfig:
          cpuManagerPolicy: static
          cpuManagerReconcilePeriod: 5s
          reservedSystemCPUs: "{{ sap_hypervisor_node_preconfigure_cluster_config.worker_kubernetes_reserved_cpus }}"

- name: Create kubletconfig for cpumanager worker
  when: sap_hypervisor_node_preconfigure_cluster_config.worker_kubernetes_reserved_cpus is not defined
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: KubeletConfig
      metadata:
        name: cpumanager-enabled
        machineconfiguration.openshift.io/role: worker
      spec:
        machineConfigPoolSelector:
          matchLabels:
            custom-kubelet: cpumanager-enabled
        kubeletConfig:
          cpuManagerPolicy: static
          cpuManagerReconcilePeriod: 5s

- name: Include wait mcp finished updating
  ansible.builtin.include_tasks: "platform/{{ sap_hypervisor_node_preconfigure_platform }}/cluster/wait-mcp-finished-updating.yml"
