---
- name: Set virtual-host for worker nodes
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: tuned.openshift.io/v1
      kind: Tuned
      metadata:
        name: virtual-host
        namespace: openshift-cluster-node-tuning-operator
      spec:
        profile:
          - data: |
              [main]
              include=virtual-host
            name: virtual-host
        recommend:
          - match:
              - label: "node-role.kubernetes.io/worker"
            priority: 10
            profile: virtual-host
