---

# vars file for redhat_ocp_virt

# Install and configure the host path provisioner (hpp) for a local storage disk
sap_hypervisor_node_preconfigure_install_hpp: false

# Install the trident NFS storage provider
sap_hypervisor_node_preconfigure_install_trident: false

# URL of the trident installer package to use
sap_hypervisor_node_preconfigure_install_trident_url: https://github.com/NetApp/trident/releases/download/v23.10.0/trident-installer-23.10.0.tar.gz

# should SRIOV be enabled for unsupported NICs
sap_hypervisor_node_preconfigure_sriov_enable_unsupported_nics: true

# Amount of memory [GiB] to be reserved for the hypervisor on hosts >= 512GiB
sap_hypervisor_node_preconfigure_hypervisor_reserved_ram_host_ge_512: 64 # GiB

# Amount of memory [GiB] to be reserved for the hypervisor on hosts < 512GiB
sap_hypervisor_node_preconfigure_hypervisor_reserved_ram_host_lt_512: 32 # GiB

# Should the check for the minimal amount of be ignored? Minimal amount is 96 GiB
sap_hypervisor_node_preconfigure_ignore_minimal_memory_check: false

# Should the operators be installed
sap_hypervisor_node_preconfigure_install_operators: true

# Configure the workers?
sap_hypervisor_node_preconfigure_setup_worker_nodes: true
