---
- name: Patch Node Labels
  kubernetes.core.k8s_json_patch:
    kind: Node
    name: "{{ __sap_hypervisor_node_preconfigure_register_worker.name }}"
    patch:
      - op: add
        path: /metadata/labels/cpumanager
        value: True
  register: __sap_hypervisor_node_preconfigure_label_node_result


- name: Include node network
  ansible.builtin.include_tasks: node-network.yml
  with_items: "{{ __sap_hypervisor_node_preconfigure_register_worker.networks }}"
  loop_control:
    loop_var: __sap_hypervisor_node_preconfigure_register_worker_network
    index_var: __sap_hypervisor_node_preconfigure_register_worker_network_nr
  when: __sap_hypervisor_node_preconfigure_register_worker.networks is defined


# How to wait for node to be scheduleable? (NodeSchedulable)
- name: Wait for all k8s nodes to be ready
  kubernetes.core.k8s_info:
    kind: Node
  register: __sap_hypervisor_node_preconfigure_register_nodes
  until: __sap_hypervisor_node_preconfigure_register_nodes.resources | json_query('[?status.conditions[?type==`Ready` && status==`True`]].metadata.name') | length == __sap_hypervisor_node_preconfigure_register_nodes.resources | length
  retries: 90
  delay: 20
  ignore_errors: True
  changed_when: false

- name: Check and fail if any node is not ready
  fail:
    msg: "Node '{{ item.metadata.name }}' is not ready."
  loop: "{{ __sap_hypervisor_node_preconfigure_register_nodes.resources }}"
  when: not item.status.conditions | selectattr('type', 'equalto', 'Ready') | map(attribute='status') | list | first == 'True'
