---
- name: Download trident
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ sap_hypervisor_node_preconfigure_install_trident_url }}"
    dest: "{{ __sap_hypervisor_node_preconfigure_register_tmpdir.path }}/"

- name: Uninstall trident
  ansible.builtin.command: "{{ __sap_hypervisor_node_preconfigure_register_tmpdir.path }}/trident-installer/tridentctl uninstall -n trident"
  ignore_errors: true
  register: __sap_hypervisor_node_preconfigure_register_uninstall_trident
  changed_when: __sap_hypervisor_node_preconfigure_register_uninstall_trident.rc != 0

- name: Install trident
  ansible.builtin.command: "{{ __sap_hypervisor_node_preconfigure_register_tmpdir.path }}/trident-installer/tridentctl install -n trident"
  register: __sap_hypervisor_node_preconfigure_register_install_trident
  changed_when: __sap_hypervisor_node_preconfigure_register_install_trident.rc != 0

- name: Copy backend file
  ansible.builtin.template:
    src: "trident-backend.json.j2"
    dest: "{{ __sap_hypervisor_node_preconfigure_register_tmpdir.path }}/trident-backend.json"
    mode: "0644"

- name: Create trident backend
  ansible.builtin.command: "{{ __sap_hypervisor_node_preconfigure_register_tmpdir.path }}\
                            /trident-installer/tridentctl -n trident create backend -f\
                            {{ __sap_hypervisor_node_preconfigure_register_tmpdir.path }}\
                            /trident-backend.json"
  register: __sap_hypervisor_node_preconfigure_register_create_trident_backend
  changed_when: __sap_hypervisor_node_preconfigure_register_create_trident_backend.rc != 0

- name: Create storage class
  kubernetes.core.k8s:
    host: "{{ sap_hypervisor_node_preconfigure_ocp_endpoint }}"
    validate_certs: false
    api_key: "{{ __sap_hypervisor_node_preconfigure_register_openshift_auth_results.openshift_auth.api_key }}"
    kubeconfig: "{{ sap_hypervisor_node_kubeconfig }}"
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: nas
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: csi.trident.netapp.io
      parameters:
        backendType: "{{ sap_hypervisor_node_preconfigure_cluster_config.trident.storage_driver }}"
        snapshots: "true"
        provisioningType: "thin"
        encryption: "false"
