---
- name: Create the SRIOV Operator namespace
  kubernetes.core.k8s:
    host: "{{ sap_hypervisor_node_preconfigure_ocp_endpoint }}"
    ca_cert: "{{ sap_hypervisor_node_preconfigure_ca_cert}}"
    api_key: "{{ __sap_hypervisor_node_preconfigure_register_openshift_auth_results.openshift_auth.api_key }}"
    kubeconfig: "{{ sap_hypervisor_node_preconfigure_kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: openshift-sriov-network-operator

- name: Create the SRIOV Operator namespace
  kubernetes.core.k8s:
    host: "{{ sap_hypervisor_node_preconfigure_ocp_endpoint }}"
    ca_cert: "{{ sap_hypervisor_node_preconfigure_ca_cert}}"
    api_key: "{{ __sap_hypervisor_node_preconfigure_register_openshift_auth_results.openshift_auth.api_key }}"
    kubeconfig: "{{ sap_hypervisor_node_preconfigure_kubeconfig }}"
    state: present
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: sriov-network-operators
        namespace: openshift-sriov-network-operator
      spec:
        targetNamespaces:
          - openshift-sriov-network-operator

- name: Create the SRIOV Operator namespace
  kubernetes.core.k8s:
    host: "{{ sap_hypervisor_node_preconfigure_ocp_endpoint }}"
    ca_cert: "{{ sap_hypervisor_node_preconfigure_ca_cert}}"
    api_key: "{{ __sap_hypervisor_node_preconfigure_register_openshift_auth_results.openshift_auth.api_key }}"
    kubeconfig: "{{ sap_hypervisor_node_preconfigure_kubeconfig }}"
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: sriov-network-operator-subscription
        namespace: openshift-sriov-network-operator
      spec:
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        name: sriov-network-operator
        channel: "stable"

- name: Pause to give operator a chance to install
  ansible.builtin.pause:
    minutes: 3


- name: Enable unsupported NICs for SRIOV usage
  when: sap_hypervisor_node_preconfigure_sriov_enable_unsupported_nics
  kubernetes.core.k8s:
    host: "{{ sap_hypervisor_node_preconfigure_ocp_endpoint }}"
    ca_cert: "{{ sap_hypervisor_node_preconfigure_ca_cert}}"
    api_key: "{{ __sap_hypervisor_node_preconfigure_register_openshift_auth_results.openshift_auth.api_key }}"
    kubeconfig: "{{ sap_hypervisor_node_preconfigure_kubeconfig }}"
    state: patched
    definition:
      apiVersion: sriovnetwork.openshift.io/v1
      kind: SriovOperatorConfig
      spec:
        enableOperatorWebhook: false
