---
- name: Personalize template
  ansible.builtin.template:
    src: 99-kargs-worker.yml.j2
    dest: "{{ __sap_hypervisor_node_preconfigure_register_tmpdir.path }}/99-kargs-{{ __sap_hypervisor_node_preconfigure_register_worker_name }}.yml.j2"
    mode: "0644"

- name: Enable hugepages
  kubernetes.core.k8s:
    host: "{{ sap_hypervisor_node_preconfigure_ocp_endpoint }}"
    validate_certs: false
    api_key: "{{ __sap_hypervisor_node_preconfigure_register_openshift_auth_results.openshift_auth.api_key }}"
    kubeconfig: "{{ sap_hypervisor_node_kubeconfig }}"
    state: present
    src: "{{ __sap_hypervisor_node_preconfigure_register_tmpdir.path }}/99-kargs-{{ __sap_hypervisor_node_preconfigure_register_worker_name }}.yml.j2"
