---
- name: Label worker with invtsc flag
  kubernetes.core.k8s:
    host: "{{ sap_hypervisor_node_preconfigure_ocp_endpoint }}"
    ca_cert: "{{ sap_hypervisor_node_preconfigure_ca_cert}}"
    api_key: "{{ __sap_hypervisor_node_preconfigure_register_openshift_auth_results.openshift_auth.api_key }}"
    kubeconfig: "{{ sap_hypervisor_node_preconfigure_kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: default
        labels:
          'feature.node.kubernetes.io/cpu-feature-invtsc': enabled
