---
- name: Gather Facts
  ansible.builtin.gather_facts:

- name: Create Tempdir
  ansible.builtin.tempfile:
    state: directory
    suffix: "_sap_hypervisor_node_preconfigure"
  register: __sap_hypervisor_node_preconfigure_register_tmpdir

- name: "Create VM namespace {{ sap_hypervisor_node_preconfigure_cluster_config.vm_namespace }}"
  kubernetes.core.k8s:
    host: "{{ sap_hypervisor_node_preconfigure_ocp_endpoint }}"
    ca_cert: "{{ sap_hypervisor_node_preconfigure_ca_cert}}"
    api_key: "{{ __sap_hypervisor_node_preconfigure_register_openshift_auth_results.openshift_auth.api_key }}"
    kubeconfig: "{{ sap_hypervisor_node_preconfigure_kubeconfig }}"
    name: "{{ sap_hypervisor_node_preconfigure_cluster_config.vm_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
