---
- name: Set virtual-host for worker nodes
  kubernetes.core.k8s:
    host: "{{ sap_hypervisor_node_preconfigure_ocp_endpoint }}"
    validate_certs: false
    api_key: "{{ __sap_hypervisor_node_preconfigure_register_openshift_auth_results.openshift_auth.api_key }}"
    kubeconfig: "{{ sap_hypervisor_node_kubeconfig }}"
    state: present
    definition:
      apiVersion: tuned.openshift.io/v1
      kind: Tuned
      metadata:
        name: virtual-host
        namespace: openshift-cluster-node-tuning-operator
      spec:
        profile:
          - data: |
                [main]
                include=virtual-host
            name: virtual-host
        recommend:
          - match:
              - label: "node-role.kubernetes.io/worker"
            priority: 10
            profile: virtual-host
