---
- name: Ansible Play to run sap_hypervisor_node_preconfigure Ansible Role for Red Hat OpenShift
  hosts: all
  gather_facts: false
  vars:
    sap_hypervisor_node_preconfigure_platform: redhat_ocp_virt
  tasks:

    - name: Use kubeconfig file specified in environment variable K8S_AUTH_KUBECONFIG | KUBECONFIG if sap_hypervisor_node_preconfigure_ocp_kubeconfig_path is not defined.
      when: >
        sap_hypervisor_node_preconfigure_kubeconfig is not defined or
        sap_hypervisor_node_preconfigure_kubeconfig == None or
        sap_hypervisor_node_preconfigure_kubeconfig == ''
      ansible.builtin.set_fact:
        sap_hypervisor_node_preconfigure_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') | default(lookup('env', 'KUBECONFIG'), true) }}"

    - name: Ensure that kubeconfig is set
      ansible.builtin.assert:
        that:
          - sap_hypervisor_node_preconfigure_kubeconfig is defined
          - sap_hypervisor_node_preconfigure_kubeconfig is not none
          - sap_hypervisor_node_preconfigure_kubeconfig | length > 0
        fail_msg: "sap_hypervisor_node_preconfigure_kubeconfig is required."

    - name: Create Tempdir on jumphost
      ansible.builtin.tempfile:
        state: directory
        suffix: "_sap_hypervisor_node_preconfigure"
      register: __sap_hypervisor_node_preconfigure_register_tmpdir_jumphost

    - name: Invoke role with credentials set as environment variables
      delegate_to: "{{ inventory_hostname }}"
      delegate_facts: true
      environment:
        KUBECONFIG: "{{ sap_hypervisor_node_preconfigure_kubeconfig }}"
        K8S_AUTH_KUBECONFIG: "{{ sap_hypervisor_node_preconfigure_kubeconfig }}"
      block:

        - name: Include sap_hypervisor_node_preconfigure Ansible Role
          ansible.builtin.include_role:
            name: community.sap_infrastructure.sap_hypervisor_node_preconfigure

      always:

        - name: Remove temporary directory
          ansible.builtin.file:
            state: absent
            path: "{{ __sap_hypervisor_node_preconfigure_register_tmpdir_jumphost.path }}"
