---

- name: Ansible Play to run sap_vm_provision Ansible Role
  hosts: all
  gather_facts: true
  serial: 1


#      ansible.builtin.include_tasks: "{{ 'platform_' + sap_vm_provision_iac_type }}/{{ sap_vm_provision_iac_platform }}/execute_main.yml"



  vars:
#    sap_vm_provision_platform: redhat_ocp_virt
    sap_vm_provision_iac_type: ansible
    sap_vm_provision_iac_platform: redhat_ocp_virt 
    sap_vm_provision_host_specification_plan: example_host_specification_plan
    sap_vm_provision_kubeconfig: "{{ lookup( 'ansible.builtin.env', 'K8S_AUTH_KUBECONFIG') }}"
    sap_vm_provision_kubevirt_kubeconfig_path: "{{ lookup( 'ansible.builtin.env', 'K8S_AUTH_KUBECONFIG') }}"

    # XXX namespace?
    scaleout_origin_host_spec: lu0567

    # XXX Naming w/ kubevirt?
    sap_vm_provision_kubevirt_os_user: minion
    sap_vm_provision_kubevirt_os_user_password: banana

    # XXX handle if not defined
    sap_vm_provision_ssh_host_public_key_file_path: /home/nils/.ssh/id_rsa.pub 

    # XXX namespace?
    sap_vm_provision_kubevirt_target_namespace: openshift-sriov-network-operator

    # XXX handle DL/existing usage
    sap_vm_provision_kubevirt_vm_host_os_image_url: "docker://registry.redhat.io/rhel8/rhel-guest-image:9.2.0"
    sap_vm_provision_kubevirt_vm_host_os_image_base_url: "docker://registry.redhat.io/rhel8/rhel-guest-image:"
    sap_vm_provision_kubevirt_os_image_namespace: openshift-virtualization-os-images



  environment:
    KUBECONFIG: "{{ sap_vm_provision_kubeconfig }}"
    K8S_AUTH_KUBECONFIG: "{{ sap_vm_provision_kubeconfig }}"
    K8S_AUTH_USERNAME: "kubeadmin"
    K8S_AUTH_PASSWORD: "T4Zq8-RewKG-XC8DN-UmokT" 

  tasks:
    - name: Print K8S_AUTH_KUBECONFIG
      debug: var=K8S_AUTH_KUBECONFIG

    - name: Print sap_vm_provision_kubeconfig
      debug: var=sap_vm_provision_kubeconfig

    - name: Sleep so we can investigate the container environement
      pause:
        minutes: 5
      when: sap_vm_provision_debug is defined and sap_vm_provision_debug == true

    - name: Include sap_vm_provision Ansible Role
      ansible.builtin.include_role:
        name: sap_vm_provision
