---

- name: Ansible Play to run sap_hypervisor_node_preconfigure Ansible Role
  hosts: all
  gather_facts: true
  serial: 1

  vars:
    sap_hypervisor_node_platform: redhat_ocp_virt
#    sap_hypervisor_node_kubeconfig: "{{ lookup( 'ansible.builtin.env', 'K8S_AUTH_KUBECONFIG') }}"

#    host: "{{ sap_hypervisor_node_preconfigure_ocp_endpoint }}"
#    username: "{{ sap_hypervisor_node_preconfigure_ocp_admin_username }}"
#    password: "{{ sap_hypervisor_node_preconfigure_ocp_admin_password }}"
#    validate_certs: false
#    api_key: "{{ __sap_hypervisor_node_preconfigure_register_openshift_auth_results.openshift_auth.api_key }}"
#    kubeconfig: "{{ sap_hypervisor_node_kubeconfig }}"


  environment:
    KUBECONFIG: "{{ sap_hypervisor_node_preconfigure_kubeconfig }}"
#    K8S_AUTH_KUBECONFIG: "{{ sap_hypervisor_node_preconfigure_kubeconfig }}"

  tasks:
    - name: Print sap_hypervisor_node_kubeconfig
      debug: var=sap_hypervisor_node_kubeconfig

    - name: Sleep so we can investigate the container environement
      pause:
        minutes: 5
      when: sap_hypervisor_node_preconfigure_debug is defined and sap_hypervisor_node_preconfigure_debug == true

    - name: Include sap_hypervisor_node_preconfigure Ansible Role
      ansible.builtin.include_role:
        name: sap_hypervisor_node_preconfigure
