---

- name: Ansible Play to run sap_hypervisor_node_preconfigure Ansible Role
  hosts: all
  gather_facts: true
  serial: 1

  vars:
    sap_hypervisor_node_platform: redhat_ocp_virt
#    sap_hypervisor_node_kubeconfig: "{{ lookup( 'ansible.builtin.env', 'K8S_AUTH_KUBECONFIG') }}"

  environment:
    KUBECONFIG: "{{ sap_hypervisor_node_kubeconfig }}"
    K8S_AUTH_KUBECONFIG: "{{ sap_hypervisor_node_kubeconfig }}"

  tasks:
    - name: Print sap_hypervisor_node_kubeconfig
      debug: var=sap_hypervisor_node_kubeconfig

    - name: Sleep so we can investigate the container environement
      pause:
        minutes: 5
      when: sap_hypervisor_node_preconfigure_debug is defined and sap_hypervisor_node_preconfigure_debug == true

    - name: Include sap_hypervisor_node_preconfigure Ansible Role
      ansible.builtin.include_role:
        name: sap_hypervisor_node_preconfigure
