---
- name: Wait for worker MachineConfigPool to start updating
  kubernetes.core.k8s_info:
    api_version: machineconfiguration.openshift.io/v1
    kind: MachineConfigPool
    name: worker
  ignore_errors: true
  retries: 5
  delay: 60
  register: __sap_hypervisor_node_preconfigure_register_mcp_info
  until: (__sap_hypervisor_node_preconfigure_register_mcp_info.resources[0].status.conditions | selectattr('type', 'equalto', 'Updating'))[0].status == true

- name: Wait for worker MachineConfigPool to be updated
  kubernetes.core.k8s_info:
    api_version: machineconfiguration.openshift.io/v1
    kind: MachineConfigPool
    name: worker
  retries: 60
  delay: 60
  register: __sap_hypervisor_node_preconfigure_register_mcp_info
  until: (__sap_hypervisor_node_preconfigure_register_mcp_info.resources[0].status.conditions | selectattr('type', 'equalto', 'Updated'))[0].status == true
